FROM python:3.11

# Required: install runit and procps
RUN apt-get update && apt-get install -y runit procps \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

COPY ./requirements.txt .
# Install packages required by the application
RUN pip install -r requirements.txt
# Set port
ENV PORT 8000
EXPOSE $PORT
CMD ["pfapp"]